CREATE DATABASE BD_ACADEMIA

USE BD_ACADEMIA

CREATE TABLE Instrutor(
    CPF INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Telefone VARCHAR(11) 
)

SELECT * FROM Instrutor


CREATE TABLE Matricula(
    Id_Matricula INTEGER  NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    Data_Matricula  DATE NOT NULL,
    Data_Vencimento DATE NOT NULL,
    CPF_Instrutor INTEGER FOREIGN KEY REFERENCES Instrutor(CPF)
)

SELECT * FROM Matricula


CREATE TABLE Aluno(
    CPF INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Altura FLOAT,
    Peso INTEGER,
    Telefone VARCHAR(20),
    Id_Matricula INTEGER FOREIGN KEY REFERENCES Matricula(Id)
)


SELECT * FROM Aluno