CREATE DATABASE BD_ACADEMIA

USE BD_ACADEMIA

CREATE TABLE Instrutor(
    CPF INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Telefone VARCHAR(11) 
)