CREATE DATABASE BD_ACADEMIA

USE BD_ACADEMIA

CREATE TABLE Instrutor(
    CPF INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Telefone VARCHAR(17)
)

SELECT * FROM Instrutor


CREATE TABLE Matricula(
    Id INTEGER  NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Data_Matricula  DATE NOT NULL,
    Data_Vencimento DATE,
    CPF_Instrutor INTEGER NOT NULL FOREIGN KEY REFERENCES Instrutor(CPF)
)

SELECT * FROM Matricula


CREATE TABLE Aluno(
    CPF INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Altura FLOAT,
    Peso INTEGER,
    Telefone VARCHAR(20),
    Id_Matricula INTEGER NOT NULL FOREIGN KEY REFERENCES Matricula(Id)
)

SELECT * FROM Aluno


CREATE TABLE Atividade(
    Id INTEGER NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    CPF_Instrutor INTEGER NOT NULL FOREIGN KEY REFERENCES Instrutor(CPF)
)

SELECT * FROM Atividade


CREATE TABLE Turma(
    Id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Horario_Aula INTEGER NOT NULL,
    Id_Atividade INTEGER NOT NULL FOREIGN KEY REFERENCES Atividade(Id)
)

SELECT * FROM Turma


CREATE TABLE Aluno_Turma(
    Id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Id_Turma INTEGER NOT NULL FOREIGN KEY REFERENCES Turma(Id),
    CPF_Aluno INTEGER NOT NULL FOREIGN KEY REFERENCES Aluno(CPF)
)

SELECT * FROM Aluno_Turma


CREATE TABLE Ausencia(
    Id INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Data_Ausencia DATE NOT NULL,
    Id_AlunoTurma INTEGER NOT NULL FOREIGN KEY REFERENCES Aluno_Turma(Id)
)

SELECT * FROM Ausencia